config/routes.rb
Rails.application.routes.draw do

  resources :licenses do
    post 'revert', :on => :member
    get 'list_versions', :on => :member
  end
  mount Ckeditor::Engine => '/ckeditor'
  get 'spelling', to: 'spellings#index'
  get 'spelling/play', to: 'spellings#play'
  get 'spelling/session_results', to: 'spellings#session_results'
  post 'spelling/check', to: 'spellings#check'
  get 'spelling/siguiente', to: 'spellings#siguiente'


  # API
  namespace :api do
    namespace :v1 do
      get 'palabra/:word', to: 'endpoints#palabra'
      get 'list_words_with_this_length/:length', to: 'list_words_with_this_length#list'
    end
  end

  mount Commontator::Engine => '/commontator'

  resources :memory_games do
    get :"autocomplete_word_name", :on => :collection
  end

  MODEL_TABS.each do |model|
    resources model.to_sym do
      post 'revert', :on => :member
      post 'soft_delete', :on => :member
      post 'soft_restore', :on => :member
      get 'list_versions', :on => :member
      get :"autocomplete_#{model.singularize}_name", :on => :collection
    end
  end



  HIDDEN_MODELS.each do |model|
    resources model.to_sym do
      post 'revert', :on => :member
      get 'list_versions', :on => :member
    end
  end



  devise_for :users, path_prefix: 'auth', controllers: {registrations: 'registrations',
                                                        confirmations: 'confirmations' ,
                                                        passwords: 'passwords' }


  resources :users do
    post 'revert', :on => :member
    get 'list_versions', :on => :member
  end

  # require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'
  #
  get 'frontends/_vote_reset', to: 'frontends#_vote_reset'
  get 'frontends/_vote_for', to: 'frontends#_vote_for'
  get 'frontends/_vote_against', to: 'frontends#_vote_against'
  get 'frontends/_vote_reset_thumbs', to: 'words#_vote_reset_thumbs'
  get 'frontends/_vote_for_thumbs', to: 'words#_vote_for_thumbs'
  get 'frontends/_vote_against_thumbs', to: 'words#_vote_against_thumbs'
  get 'frontends/_palabra_mas_resien', to: 'frontends#_palabra_mas_resien'
  get 'frontends/_palabra_mas_mira', to: 'frontends#_palabra_mas_mira'
  get 'frontends/rapport', to: 'frontends#rapport'


  get 'palabra/:word', to: 'frontends#palabra'
  post 'palabra', to: 'frontends#search'

  get 'my_profile', to: 'frontends#my_profile'

  # post 'tra_palabra', to: 'frontends#tra_palabra'
  # post 'check_text', to: 'frontends#check_text'


  get 'glosario/:id', to: 'glossaries#show_glossary'
  match 'glosario/:id/edit_glossary', to: 'glossaries#edit_glossary', via: [:get, :post]
  get 'fuente/:id', to: 'sources#show_source'
  get 'meta/:id', to: 'goals#show_goal'

  get 'dijkhoff_goals', to: 'goals#show_dijkhoff_goals'


  get '/flora', to: 'frontends#galeria'
  get '/founa', to: 'frontends#galeria'
  get '/músika', to: 'frontends#galeria'
  get '/musika', to: redirect(CGI.escape('músika'))
  get '/konstrukshon', to: 'frontends#galeria'

  get '/endings', to: 'frontends#endings'



  get 'memory_games/:id/play_memory_game', to: 'memory_games#play_memory_game'
  match 'memory_games/:id/edit_memory_game', to: 'memory_games#edit_memory_game', via: [:get, :post]
  get 'memory_game', to: 'memory_games#play_random_memory_game'
  get 'memory_game_flora', to: 'memory_games#play_random_memory_game_flora'
  get 'memory_game_founa', to: 'memory_games#play_random_memory_game_founa'
  get 'memory_game_musika', to: 'memory_games#play_random_memory_game_musika'

  get 'slide_games/:id/edit_game', to: 'slide_games#edit_game'
  get 'slide_games/:id/play_game', to: 'slide_games#play_game'
  post 'slide_games/:id/edit_game', to: 'slide_games#edit_game'
  root :to => 'frontends#index'




end

app/controllers/spellings_controller.rb
class SpellingsController < ApplicationController
  layout 'frontends'
  #load_and_authorize_resource :class => false

  def index
    authorize!(:index, :spellings)
    @spelling_groups = SpellingGroup.all
    @leaderboard = User.leaderboard.limit(10)
  end

  def play
    authorize!(:play, :spellings)
    @spelling_group = SpellingGroup.find_by_id params[:spelling_group]
    words = words_for_training_session params[:spelling_group]
    create_words_session_var words
    initialize_spelling_tries
    @word = next_word_from words
    @spelling_session = current_user.spelling_sessions.create
  end

  def check
    authorize!(:check, :spellings)

    next_word = ''
    word = Word.find params[:id]
    word_spelling = word.name.strip
    answer = params[:answer]

    if answer == word_spelling
      check = 'good'
      delete_from_words_session_var word.id
      tries = initialize_spelling_tries
      next_word = next_word_from words_in_session_var
    else
      tries = update_spelling_tries
    end

    word_spelling = word_spelling.chars.join '-'
    create_spelling_try params[:session_id], answer, check, word

    if tries > 2
      initialize_spelling_tries
      next_word = next_word_from words_in_session_var
    end

    respond_to do |format|
      format.html # contact.html.erb
      format.json {
        render json: {check: check,
          answer: answer,
          next_word: next_word,
          tries: tries,
          word_spelling: word_spelling
        }
      }
    end
  end

  def siguiente
    delete_from_words_session_var params[:id].to_i unless params[:id].empty?
    next_word = next_word_from words_in_session_var

    respond_to do |format|
      format.html # contact.html.erb
      format.json {
        render json: { next_word: next_word }
      }
    end
  end

  def session_results
    authorize!(:session_results, :spellings)
    @SpellingSession = SpellingSession.find(params[:session_id])
    @points = @SpellingSession.spelling_tries.sum(:points)
  end

  private

  def next_word_from words
    word = Word.find_by_id words.sample
    return '' if word.nil?
    hash_from_word word
  end

  def hash_from_word word
    {
      id: word.id,
      picture: word.pictures.sample.image.url,
      recording: word.recordings.sample.audio.url
    }
  end

  def words_for_training_session spelling_group_id = nil
    if spelling_group_id.nil?
      Word.has_pictures.has_recordings.limit(10).pluck(:id)
    else
      spelling_group = SpellingGroup.find(spelling_group_id)
      spelling_group.words.has_pictures.has_recordings.limit(10).pluck(:id)
    end
  end

  def create_words_session_var words
    session[:training_session_words] = words
  end

  def delete_from_words_session_var word_id
    session[:training_session_words].delete(word_id)
  end

  def words_in_session_var
    session[:training_session_words]
  end

  def initialize_spelling_tries
    session[:spelling_tries] = 1
  end

  def update_spelling_tries
     initialize_spelling_tries and return if session[:spelling_tries].nil?
    session[:spelling_tries] += 1
  end

  def create_spelling_try session_id, answer, check, word
    spelling_session = SpellingSession.find(session_id)
    session_try = spelling_session.spelling_tries.build
    session_try.user_input = answer
    session_try.word_id = word.id
    session_try.correct = check == 'good' ? true : false
    session_try.points = check == 'good' ? 5 : -1
    session_try.save
  end
end

app/views/spellings/index.html.erb
<div class="columns small-12 medium-6 large-3  bordered">
  <h2>Spèl-spèl</h2>
  <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
  <div class="text-center">
    <%= link_to "Play", spelling_play_path, class: [:button, :rounded] %>
  </div>
</div>
<div class="columns small-12 medium-6 large-6  bordered">
  <% @spelling_groups.each do |spelling_group| %>
    <div class="columns panel large-4">
      <%= image_tag spelling_group.image.palm.url, class: 'spelling-group-picture' %>
      <h5><%= spelling_group.name %></h5>
      <p><%= spelling_group.words.count %> palabra</p>
      <p><%= spelling_group.description %></p>
      <%= link_to "Play", spelling_play_path(spelling_group: spelling_group.id), class: [:button, :rounded] %>
    </div>
  <% end %>
</div>
<div class="columns small-12 medium-6 large-3  bordered ">
  <h2>Leaderboard</h2>
  <table>
    <thead>
      <tr>
        <th>Usadó</th>
        <th>Punto</th>
      </tr>
    </thead>
    <tbody>
      <% @leaderboard.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.spelling_tries.sum(:points) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/spellings/play.html.erb
<div class="columns small-12 medium-6 large-12 bordered">
  <div class="columns small-12 medium-6 large-3 text-center">
    <% if @spelling_group. nil? %>
      <h3>grupo: general</h3>
    <% else %>
      <h3>grupo: <%= @spelling_group.name %></h3>
    <% end %>
  </div>
  <div class="columns small-12 medium-6 large-6 text-center">
    <img id="spelling_picture" class="float-center" src="<%= @word[:picture]%>">
    <audio id="spelling_audio" controls="controls" src="<%= @word[:recording]%>"></audio>
    <%= hidden_field_tag 'id', @word[:id] %>
    <%= hidden_field_tag 'session_id', @spelling_session.id %>
    <%= text_field_tag 'answer' %>
    <a id="check-button" class="button rounded" href="#">Chèk</a>
  </div>
  <div class="columns small-12 medium-6 large-3 text-center">
    <%= link_to "Stop", spelling_path, class: [:button, :rounded] %>
  </div>
</div>
<div id="modal-good" class="reveal-modal tiny" class="reveal-modal" data-reveal data-reveal data-options="close_on_background_click:false;close_on_esc:false;">
  <h2 id="modalTitle" class="text-center"><i class="fi-check large"></i> korekto!</span></h2>
  <p class="text-center"><i class="fi-plus"></i> 5</p>
  <p class="text-center"><a id='siguiente-button' class="button rounded" href="#">Siguiente</a></p>
</div>
<div id="modal-wrong" class="reveal-modal tiny" class="reveal-modal" data-reveal data-reveal data-options="close_on_background_click:false;close_on_esc:false;">
  <h2 id="modalTitle" class="text-center"><i class="fi-x large"></i> purba un bia mas!</h2>
  <p class="text-center"><i class="fi-minus"></i> 1</p>
  <p class="text-center"><a id='bon-button' class="button rounded" href="#">bon!</a></p>
</div>
<div id="modal-after-2-tries" class="reveal-modal tiny" class="reveal-modal" data-reveal data-reveal data-options="close_on_background_click:false;close_on_esc:false;">
  <h2 id="modalTitle" class="text-center"><i class="fi-info large"></i> <span id="correct-spelling"></span></h2>
  <p class="text-center">esaki ta e spèlmentu korekto</p>
  <p class="text-center">
    <a id='ripiti-button' class="button rounded" href="#">Ripití</a>
    <a id='siguiente-button' class="button rounded" href="#">Siguiente</a>
  </p>
</div>

app/views/spellings/session_results.erb
<div class="columns small-12 medium-6 large-4  bordered text-center">
  <h2>Bo a gana</h2>
  <p><span class="points-number"><%= @points %></span> punto</p>
</div>
<div class="columns small-12 medium-6 large-4  bordered">
  <h2>Lista di palabra</h2>
  <table>
    <thead>
      <tr>
        <th>Palabra</th>
        <th>kon ba skirbié </th>
        <th>korekto?</th>
        <th>punto</th>
      </tr>
    </thead>
    <tbody>
      <% @SpellingSession.spelling_tries.each do |try| %>
        <tr>
          <td><%= try.word.name %></td>
          <td><%= try.user_input %></td>
          <td><%= raw try.correct ? '<i class="fi-check"></i>' : '<i class="fi-x"></i>' %></td>
          <td><%= try.points %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="columns small-12 medium-6 large-4 bordered text-center">
  <%= link_to "Hunga atrobe", spelling_play_path, class: [:button, :rounded] %>
  <%= link_to "Bai página prinsipal", spelling_path, class: [:button, :rounded] %>
</div>